apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-w08e1
type: Opaque
data:
  # PostgreSQL Credentials
  POSTGRES_USER: "cG9zdGdyZXM="
  POSTGRES_PASSWORD: "cGFzc3dvcmQ="

  # Azure Storage Account (for product-service uploads)
  AZURE_STORAGE_ACCOUNT_NAME: "YXJwaXRjcmVkaXRzdG9yYWdl"
  AZURE_STORAGE_ACCOUNT_KEY: "a1p6bU4vU3dhWENwYmRWVk40eU9KN2VyZE1ndlk4bTZGZHRMclRwdmxTN0tUZkJsdDY3b0x5WlN0bVlrUXBldEFuUVZ0RTV0OE90SCtBU3RacUNDNVE9PQ=="
