name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Request ID token
      id: get_id_token
      uses: actions/github-script@v6
      with:
        script: |
          const token = await core.getIDToken();
          core.setOutput("id_token", token);

    - name: Log in to Azure using federated token
      run: |
        az login --federated-token "${{ steps.get_id_token.outputs.id_token }}" \
                 --service-principal \
                 --tenant "${{ secrets.AZURE_TENANT_ID }}" \
                 --username "${{ secrets.AZURE_CLIENT_ID }}"

    - name: Log in to ACR
      run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

    - name: Build and push order_service image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/order-service:latest ./backend/order_service
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/order-service:latest

    - name: Build and push product_service image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/product-service:latest ./backend/product_service
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/product-service:latest
